# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0011_auto_20180620_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('file', models.FileField(upload_to='UpFile/%Y/%m', verbose_name='文件路径')),
                ('detail', models.TextField(verbose_name='上传文件的更改描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '上传文件',
                'verbose_name': '上传文件',
            },
        ),
        migrations.CreateModel(
            name='VesionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test.iso', max_length=20, verbose_name='文件名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Version', verbose_name='所属版本')),
            ],
            options={
                'verbose_name_plural': '版本文件',
                'verbose_name': '版本文件',
            },
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='versionfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='changefile.VesionFile', verbose_name='所属版本文件'),
        ),
    ]
