# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-26 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeferentFileNameVesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='更改的文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '版本文件变化',
                'verbose_name_plural': '版本文件变化',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_sn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='机器号')),
                ('version_sn', models.CharField(default='2.0.1', max_length=20, verbose_name='版本号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '远程机器',
                'verbose_name_plural': '远程机器',
            },
        ),
        migrations.CreateModel(
            name='MachineChangeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_sn', models.CharField(default='2.0.1', max_length=20, verbose_name='版本号')),
                ('is_update', models.BooleanField(default=False, verbose_name='是否更新')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Machine', verbose_name='机器')),
            ],
            options={
                'verbose_name': '机器更新状态',
                'verbose_name_plural': '机器更新状态',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='课程2.0', max_length=20, verbose_name='版本名')),
                ('edition_sn', models.CharField(default='2.0.1', max_length=20, verbose_name='版本号')),
                ('file', models.FileField(blank=True, null=True, upload_to='Version/%Y/%m', verbose_name='版本所在位置')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_changefile', models.BooleanField(default=False, verbose_name='更新文件')),
            ],
            options={
                'verbose_name': '系统版本',
                'verbose_name_plural': '系统版本',
            },
        ),
        migrations.AddField(
            model_name='deferentfilenamevesion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Version', verbose_name='当前版本'),
        ),
    ]
