# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-28 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test.ios-2.0', max_length=20, verbose_name='文件名—编号')),
                ('file', models.FileField(upload_to='UpFile/%Y/%m', verbose_name='文件路径')),
                ('detail', models.TextField(verbose_name='上传文件的更改描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='课程2.0', max_length=20, verbose_name='版本名')),
                ('number', models.CharField(default='2.0.1', max_length=20, verbose_name='版本号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '系统版本',
                'verbose_name_plural': '系统版本',
            },
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Version', verbose_name='所属版本'),
        ),
    ]
