# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Version/%Y/%m', verbose_name='版本所在位置'),
        ),
    ]
