# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180529_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test.iso', max_length=20, verbose_name='文件名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Version', verbose_name='所属版本')),
            ],
            options={
                'verbose_name_plural': '版本文件',
                'verbose_name': '版本文件',
            },
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='version',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(default='1.0', max_length=20, verbose_name='版本号'),
        ),
    ]
