# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180601_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='name',
            new_name='number',
        ),
    ]
