# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180601_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='versionfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.VesionFile', verbose_name='所属版本文件'),
        ),
    ]
