# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 23:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20180605_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineChangeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_sn', models.CharField(default='2.0.1', max_length=20, verbose_name='版本号')),
                ('is_update', models.BooleanField(default=False, verbose_name='是否更新')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Machine', verbose_name='机器')),
            ],
            options={
                'verbose_name': '机器更新状态',
                'verbose_name_plural': '机器更新状态',
            },
        ),
    ]
