# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_machinechangestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='versionfile',
        ),
        migrations.RemoveField(
            model_name='vesionfile',
            name='version',
        ),
        migrations.AddField(
            model_name='version',
            name='is_changefile',
            field=models.BooleanField(default=False, verbose_name='更新文件'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.DeleteModel(
            name='VesionFile',
        ),
    ]
