# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20180620_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferentFileNameVesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='更改的文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Version', verbose_name='当前版本')),
            ],
            options={
                'verbose_name_plural': '版本文件变化',
                'verbose_name': '版本文件变化',
            },
        ),
    ]
