# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_deferentfilenamevesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='number',
        ),
    ]
