# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10),
        ),
    ]
